# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kategoriview.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem
class Ui_kategori(object):
    def setupUi(self, kategori):
        Kategori.setObjectName("kategori")
        Kategori.resize(463, 481)
        self.horizontalLayoutWidget = QtWidgets.QWidget(kategori)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 100, 441, 51))

        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)

        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonInsert = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonInsert.setFont(font)
        self.pushButtonInsert.setObjectName("pushButtonInsert")
        self.horizontalLayout.addWidget(self.pushButtonInsert)
        self.verticalLayoutWidget = QtWidgets.QWidget(kategori)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 10, 281, 80))

        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)

        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEditId = QtWidgets.QLineEdit(self.verticalLayoutWidget)

        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditId.setFont(font)
        self.lineEditId.setObjectName("lineEditId")
        self.verticalLayout.addWidget(self.lineEditId)
        self.lineEditName = QtWidgets.QLineEdit(self.verticalLayoutWidget)

        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditName.setFont(font)
        self.lineEditName.setObjectName("lineEditName")
        self.verticalLayout.addWidget(self.lineEditName)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(kategori)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 151, 80))

        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)

        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelId = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelId.setFont(font)
        self.labelId.setObjectName("labelId")
        self.verticalLayout_2.addWidget(self.labelId)
        self.labelName = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")
        self.verticalLayout_2.addWidget(self.labelName)
        self.labelResult = QtWidgets.QLabel(kategori)
        self.labelResult.setGeometry(QtCore.QRect(10, 160, 441, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelResult.setFont(font)
        self.labelResult.setObjectName("labelResult")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(kategori)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 200, 441, 211))

        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")

        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)

        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget_3)

        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes

        (False)

        self.verticalLayout_3.addWidget(self.tableWidget)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(kategori)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 420, 441, 51))

        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)

        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonLoad = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)

        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonLoad.setFont(font)
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        self.horizontalLayout_2.addWidget(self.pushButtonLoad)
        self.pushButtonInsert.clicked.connect(self.insertkategori)
        self.pushButton_2.clicked.connect(self.loadkategori)
        self.retranslateUi(kategori)
        QtCore.QMetaObject.connectSlotsByName(kategori)

def insertkategori(self):
    try:
        mydb = mc.connect(
        host ="localhost",
        user ="root",
        password ="",
        database ="penjualan"
        )
        cursor = mydb.cursor()
        idkat = self.lineEditID.text()
        namekat = self.lineEditKategori.text()
        sql = "INSERT INTO kategori1 (id,name) VALUES (%s,%s)"
        val = (idkat,namekat)
        cursor.execute(sql,val)
        mydb.commit()
        self.label_3.setText("Data kategori Berhasil Disimpan")
        self.lineEditId.setText("")
        self.lineEditKategori.setText("")
    except mc.Error as e:
        self.label_3.setText("Data kategori Gagal Disimpan")

def loadkategori(self):
    try:
        mydb = mc.connect(
        host ="localhost",
        user ="root",
        password ="",
        database ="penjualan"
        )
        mycursor = mydb.cursor()
        mycursor.execute("SELECT * FROM kategori1 ORDER BY ID ASC")
        result = mycursor.fetchall()
        self.tableWidget.setRowCount(0)
        for row_number, row_data in enumerate(result):
            self.tableWidget.insertRow(row_number)
        for column_number, data in enumerate(row_data):
            self.tableWidget.setItem(row_number,column_number,

        QTableWidgetItem(str(data)))

        self.label_3.setText("Data kategori Berhasil Ditampilkan")

    except mc.Error as err:
        self.label_3.setText("Data kategori Gagal DiLoad")

def retranslateUi(self, kategori):
    _translate = QtCore.QCoreApplication.translate
    kategori.setWindowTitle(_translate("kategori", "Form kategori"))
    self.pushButtonInsert.setText(_translate("kategori", "INSERT DATA"))
    self.label_1.setText(_translate("kategori", "ID kategori"))
    self.label_2.setText(_translate("kategori", "Nama kategori"))

    self.label_3.setText(_translate("kategori", "TextLabel"))
    item = self.tableWidget.horizontalHeaderItem(0)
    item.setText(_translate("kategori", "No"))
    item = self.tableWidget.horizontalHeaderItem(1)
    item.setText(_translate("kategori", "Name kategori"))
    self.pushButtonLoad.setText(_translate("kategori", "LOAD DATA"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    kategori = QtWidgets.QWidget()
    ui = Ui_kategori()
    ui.setupUi(kategori)
    kategori.show()
    sys.exit(app.exec_())